// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cloud_logic : 'enable',
aws_cloud_logic_custom : '[{"id":"t0eckzi2ll","name":"bar","description":"","endpoint":"https://t0eckzi2ll.execute-api.us-east-2.amazonaws.com/Development","region":"us-east-2","paths":["/items","/items/123"]}]',
aws_cognito_identity_pool_id : 'us-east-2:a2438f34-27d3-416e-8648-f3dedf39d0c2',
aws_cognito_region : 'us-east-2',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'cloudnine-hosting-mobilehub-1619453888',
aws_content_delivery_bucket_region : 'us-east-2',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd1ukmwt6blhzff.cloudfront.net',
aws_mobile_analytics_app_id : 'e7a66638f5aa4a318fe35b993b01c260',
aws_project_id : 'ffaf7afb-a7a6-4a5a-b941-076645f8cc23',
aws_project_name : 'CloudNine',
aws_project_region : 'us-east-2',
aws_resource_bucket_name : 'cloudnine-deployments-mobilehub-1619453888',
aws_resource_name_prefix : 'cloudnine-mobilehub-1619453888',
aws_sign_in_enabled : 'enable',
aws_user_pools : 'enable',
aws_user_pools_id : 'us-east-2_2FcDIi4CR',
aws_user_pools_mfa_type : 'OFF',
aws_user_pools_web_client_id : 'tq9tp2q6heemv0s4aafmg61pe',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});